sudo: false

cache:
  directories:
    - test/elm-stuff/build-artifacts
    - sysconfcpus

os:
  - linux

env:
  global:
    secure: "jFeqqUVpShVUJeASxUrSQi1FuZgx5Q26CARyESLQf2acizm/4yuuPFJCiws74yGbs2pfF6GwW6uPm8JQca1R69E8++1l8pufsPa9rhdeht3S+VzQVu2nLvk1uvpuWwdd0n2NS0weLX/Z71GylD4n9Yi6ERG7AV/QBCfOv5cZUz4uHAOexGifjXYoSgFQugSHk4w48K6KXeJBWkvK8xGvwsdGsGN0klWm2BOqhKjfiDOhMGdIu+6T0RAATb2vcHe1kzH26g+9deycPxtfiINFRWfzDKgwJKt2zgp4T+cmFG3V/JOemRVdau8EtvJ015ECAuI+gZ/XnsmcsYclRLQZ/jTyMHMx3HIVn6X7u+KEN+b5BwaJmUomsWOG6BWepAX1b47g4dOu8QWAuVBei3mheZUmdqwdo7XIHe6isDzFLHK+Y6U8wJD8vdsCS9q1/zseC3FkiCSKwKkX+CxG0jnM12l8eO/nA7rJ+bxo8V8P9Wdknq0My8tE+ZjfrEtwJBsrHYx3igTMLH6jyiDlYkh8cVqFKjfSKOpEuFlLYGSneJNRPA/zk34+a12Ug+fE7Ph/dhRzwHWNnI391Z12soRoZ0aawXT4MdJb627meb5JYmJp5SB/3YodL7FvQrtb4nQ9BJUcBH6whWndQyzahkwJhg1HTwKZBm0k665DfTy8Wi8="
  matrix:
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=node

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm-make with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old "$@"' > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - elm package install --yes

script:
  - cd gh_pages; elm-make --yes Main.elm; cd ..;
  - elm-test

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: gh_pages
  on:
    branch: master
